### ISSUE TITLE
nit-picky things at top of 11ty-nunjucks page

### ISSUE THREAD

**Issue by joyously** [dinhanhthi/notes#1]
I got some ideas from your page!
But I see three problems in the Installation section.
1. character not rendered in all browsers
https://github.com/dinhanhthi/notes/blob/4ced34e9565d8ed3eba4cf1d86c2a53a1760f918/posts/web-dev/2021-10-16-11ty-nunjucks.md?plain=1#L23

The first character is a finger pointing, in some browsers like Firefox. In others like Falkon, it is a box. Is this something you added with a plugin?
Here is a screenshot from Falkon:
![Falkon-Screenshot_2022-03-30_13-58-50](https://user-images.githubusercontent.com/7957680/160910646-cf9185ad-09c7-492f-a1bb-96afd851144c.png)

2. code box copies the comment also
It's cool to have code copied for you, but for command line stuff, it shouldn't have the comment copied, so I suggest you move the comment out of the code box.

3. strange sentence structure
`Depend on each theme, you should follow the installation steps given in that theme.`
This should probably be more like
`You should follow the installation steps given in the theme you choose.`

**Comment by dinhanhthi** [comment]
Hi Joy, thank you very much for your suggestions. I will correct them. 

1. i directly use the emoji characters (most of them).
2. good idea, I did not think about that. I just wanted to put each code block separately from the others. I do not like to write much outside the box. I will find another way to do this (copy without comments for example). 
3. thanks, along with the techs, I also need to improve my English :)

I am in the process of migrating my website from 11ty to Gatsby. There will be improvements with the next version :)

**Comment by dinhanhthi** [comment]
I found everywhere about that "bad" but I have my reason 😉  (before using 11ty, I actually tried gatsby 😄 )
