### ISSUE TITLE
add icons or set disable (means i don't have any image ) for skiills parted in  page about

### ISSUE THREAD

**Issue by mohammadRezaeian** [dinhanhthi/notes#13]
hi
i trying edit page about  now i know if i want my images in parted skills show i must add images into file tech.json
and now i want to know is it possible i set true or false if my skill does not have any image ?

**Comment by dinhanhthi** [comment]
Yes, you have to look at the codes that implement the site about. You have to know a little bit about nunjuck language.

**Comment by mohammadRezaeian** [comment]
I don't know anything about nunjuck
Is it possible say me ?

**Comment by dinhanhthi** [comment]
Then learn it, it's not too complicated! Please, this theme is an advanced theme. You have to read and learn to be able to use it freely.

**Comment by mohammadRezaeian** [comment]
thank you but i am not a web developer
i just wants a ready and beautiful website for write because of that i select your beautiful edition
If you don't want to help, 
I prefer to migrate to something more ready and simple
Thank you again for all your work
for shared yourself  very beautiful edition

**Comment by dinhanhthi** [comment]
I'm sorry to hear that. As I mentioned in the README, I don't have time for making this theme as a ready-to-use theme. I will do someday but I cannot promise an exact time. Good luck.
