### ISSUE TITLE
missing details for "Nunjucks inside css" section

### ISSUE THREAD

**Issue by joyously** [dinhanhthi/notes#2]
The content is only a code block, no explanation. And the Nunjucks variable reference is not escaped, so the code makes no sense when rendered.

https://github.com/dinhanhthi/notes/blob/4ced34e9565d8ed3eba4cf1d86c2a53a1760f918/posts/web-dev/2021-10-16-11ty-nunjucks.md?plain=1#L284

screenshot:
![css-Screenshot_2022-03-30_14-18-28](https://user-images.githubusercontent.com/7957680/160913799-fc028dca-fdc9-4cf4-b9bd-10106a4e65c9.png)

**Comment by dinhanhthi** [comment]
Fixed, thanks.
