### ISSUE TITLE
no code visible for custom frontmatter section

### ISSUE THREAD

**Issue by joyously** [dinhanhthi/notes#3]
I think this line has a `&` instead of a `%`

https://github.com/dinhanhthi/notes/blob/4ced34e9565d8ed3eba4cf1d86c2a53a1760f918/posts/web-dev/2021-10-16-11ty-nunjucks.md?plain=1#L487

So it renders as nothing:
![frontmatter-Screenshot_2022-03-30_14-27-01](https://user-images.githubusercontent.com/7957680/160915162-e461da69-ee8f-4a01-b44e-b36de1fb0a8b.png)

Also, the text says "your page (eg. index.js)" when it might make more sense as "your page (eg. index.md)".

**Comment by dinhanhthi** [comment]
Fixed, thanks.
