### ISSUE TITLE
missing info in "Nunjucks tags inside .md" section

### ISSUE THREAD

**Issue by joyously** [dinhanhthi/notes#6]
This section on Nunjucks inside .md makes no sense.
https://github.com/dinhanhthi/notes/blob/4ced34e9565d8ed3eba4cf1d86c2a53a1760f918/posts/web-dev/2021-10-16-11ty-nunjucks.md?plain=1#L1125

They look alike to me.
![nj-tags-Screenshot_2022-03-30_14-57-52](https://user-images.githubusercontent.com/7957680/160920318-ddb5ffec-1c3c-45ec-a9fb-31fb2adfb62f.png)

**Comment by dinhanhthi** [comment]
The problem arises from indentation when we write Markdown. I think the linter of vscode changed the formatting and they look the same.
